kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: rt53-updater
  labels:
    rt53-updater: main
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        run: rt53-updater
    spec:
      containers:
        - name: rt53-updater
          image: {{.Image}}
          imagePullPolicy: Always
          env:
            - name: NAMESPACE
              value: ato-dev
            - name: AWS_REGION
              value: us-west-2
